%if "#{==:#{E:@XDG_DATA_HOME},}"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins"
%else
set-environment -g TMUX_PLUGIN_MANAGER_PATH "#{E:@XDG_DATA_HOME}/tmux/plugins"
%endif

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",${TERM}:Tc"
# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
# underscore colours - needs tmux-3.0
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Plugins section: defining the plugins to be used with tmux
# Load the tmux-sensible plugin for setting sensible default settings for tmux
# Load the tmux-yank plugin to enable copying to system clipboard
# Load the tmux-prefix-highlight plugin to highlight the prefix key when pressed (uncomment to enable)
# Load the tpm (tmux plugin manager) to manage the plugins

# Configure prefix highlight appearance
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tpm'

set -g @prefix_highlight_show_copy_mode 'on'

set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_date_time '%k:%M %d/%m/%y'

set -g window-status-format '#I:#W'
set -g window-status-current-format '#I:#W'


setw -g mode-keys vi # Set the key bindings in copy mode to vi style

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

setw -g monitor-activity on # Monitor activity in other windows and alert when there is activity

setw -g mouse on # Enable mouse support (e.g., for selecting and resizing panes)

# toggles the mouse support and shows the current status
unbind m
bind m setw mouse\; display-message "mouse is now #{?mouse,on,off}"

set -g allow-rename off # don't rename windows automatically
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on # Ensure window index numbers get reordered on delete.


# Moving between panes with prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Bindings for resizing panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Move the current window one position to the left (previous)
bind-key P swap-window -t -1

# Move the current window one position to the right (next)
bind-key N swap-window -t +1

set-option -g status-justify centre

run-shell "#{E:TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm"
